package main

import (
	"flag"
	"fmt"
	"os"
)

const (
	VERSION  = `0.1`
	TEMPLATE = `// THIS FILE WAS AUTOGENERATED BY GO GENEREATE. DO NOT EDIT!
package %s

func init() {
	version := %s
	dynamicVersion = &version
}
`
)

func quote(value string) string {
	return "`" + value + "`"
}

func main() {
	var outfile, pkg string
	flag.StringVar(&outfile, "out", "", "output file")
	flag.StringVar(&pkg, "package", "", "target package")

	flag.Parse()

	if outfile == "" || pkg == "" {
		flag.Usage()
		os.Exit(1)
	}

	file, err := os.Create(outfile)
	if err != nil {
		panic(err)
	}

	_, err = fmt.Fprintf(file, TEMPLATE, pkg, quote(VERSION))
	if err != nil {
		panic(err)
	}

	err = file.Close()
	if err != nil {
		panic(err)
	}
}
